// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_vipernet_xyz_viper_network_types "github.com/vipernet-xyz/viper-network/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgProtoStake struct {
	PubKey       []byte                                             `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pubkey" yaml:"pubkey"`
	Chains       []string                                           `protobuf:"bytes,2,rep,name=chains,proto3" json:"chains" yaml:"chains"`
	Value        github_com_vipernet_xyz_viper_network_types.BigInt `protobuf:"bytes,3,opt,name=value,proto3,customtype=github.com/vipernet-xyz/viper-network/types.BigInt" json:"value" yaml:"value"`
	GeoZones     []string                                           `protobuf:"bytes,4,rep,name=geo_zone,proto3" json:"geo_zone" yaml:"geo_zone"`
	NumServicers int64                                              `protobuf:"varint,5,opt,name=num_servicers,proto3" json:"num_servicers" yaml:"num_servicers"`
}

func (m *MsgProtoStake) Reset()      { *m = MsgProtoStake{} }
func (*MsgProtoStake) ProtoMessage() {}
func (*MsgProtoStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}
func (m *MsgProtoStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProtoStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProtoStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProtoStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProtoStake.Merge(m, src)
}
func (m *MsgProtoStake) XXX_Size() int {
	return m.Size()
}
func (m *MsgProtoStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProtoStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProtoStake proto.InternalMessageInfo

func (*MsgProtoStake) XXX_MessageName() string {
	return "x.requestors.MsgProtoStake"
}

type MsgBeginUnstake struct {
	Address github_com_vipernet_xyz_viper_network_types.Address `protobuf:"bytes,1,opt,name=Address,proto3,casttype=github.com/vipernet-xyz/viper-network/types.Address" json:"requestor_address" yaml:"requestor_address"`
}

func (m *MsgBeginUnstake) Reset()      { *m = MsgBeginUnstake{} }
func (*MsgBeginUnstake) ProtoMessage() {}
func (*MsgBeginUnstake) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}
func (m *MsgBeginUnstake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBeginUnstake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBeginUnstake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBeginUnstake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBeginUnstake.Merge(m, src)
}
func (m *MsgBeginUnstake) XXX_Size() int {
	return m.Size()
}
func (m *MsgBeginUnstake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBeginUnstake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBeginUnstake proto.InternalMessageInfo

func (*MsgBeginUnstake) XXX_MessageName() string {
	return "x.requestors.MsgBeginUnstake"
}

type MsgUnjail struct {
	RequestorAddr github_com_vipernet_xyz_viper_network_types.Address `protobuf:"bytes,1,opt,name=RequestorAddr,proto3,casttype=github.com/vipernet-xyz/viper-network/types.Address" json:"address" yaml:"address"`
}

func (m *MsgUnjail) Reset()      { *m = MsgUnjail{} }
func (*MsgUnjail) ProtoMessage() {}
func (*MsgUnjail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}
func (m *MsgUnjail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnjail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnjail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnjail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnjail.Merge(m, src)
}
func (m *MsgUnjail) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnjail) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnjail.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnjail proto.InternalMessageInfo

func (*MsgUnjail) XXX_MessageName() string {
	return "x.requestors.MsgUnjail"
}
func init() {
	proto.RegisterType((*MsgProtoStake)(nil), "x.requestors.MsgProtoStake")
	proto.RegisterType((*MsgBeginUnstake)(nil), "x.requestors.MsgBeginUnstake")
	proto.RegisterType((*MsgUnjail)(nil), "x.requestors.MsgUnjail")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xb1, 0x6f, 0xd3, 0x40,
	0x18, 0xc5, 0x7d, 0x84, 0x24, 0xe4, 0x48, 0xa0, 0x32, 0x1d, 0xa2, 0x22, 0xdd, 0x05, 0x4f, 0x61,
	0x68, 0x22, 0x11, 0x24, 0xa4, 0x0e, 0x48, 0xf5, 0x86, 0x50, 0x10, 0x72, 0xe8, 0xd2, 0x25, 0x72,
	0x92, 0xd3, 0xf5, 0x48, 0x7c, 0x67, 0xf9, 0xec, 0x10, 0x77, 0x62, 0x82, 0x2e, 0x48, 0x8c, 0x8c,
	0x11, 0x13, 0x03, 0x7f, 0x48, 0xc7, 0x8c, 0x15, 0xc3, 0x89, 0x38, 0x4b, 0xe5, 0xa9, 0xca, 0xc8,
	0x84, 0x9c, 0x4b, 0x1b, 0x55, 0x74, 0x00, 0xb1, 0x7d, 0xef, 0x3d, 0x7f, 0xf7, 0x7e, 0xf2, 0xe9,
	0x60, 0xc9, 0x93, 0xb4, 0xe1, 0x07, 0x22, 0x14, 0xe6, 0xdd, 0x49, 0x36, 0x8c, 0xd9, 0x80, 0x04,
	0x72, 0x67, 0x9b, 0x0a, 0x2a, 0x56, 0x7e, 0x33, 0x9b, 0xf4, 0x27, 0xd6, 0xc7, 0x1c, 0xac, 0xb4,
	0x25, 0x7d, 0x9d, 0x89, 0x4e, 0xe8, 0x0e, 0x89, 0xf9, 0x14, 0x16, 0xfd, 0xa8, 0xd7, 0x1d, 0x92,
	0xb8, 0x0a, 0x6a, 0xa0, 0x5e, 0xb6, 0x1f, 0xa6, 0x0a, 0x17, 0xfc, 0xa8, 0x37, 0x24, 0xf1, 0x52,
	0xe1, 0x4a, 0xec, 0x7a, 0xa3, 0x3d, 0x4b, 0x6b, 0xcb, 0xc9, 0x82, 0x97, 0x24, 0x36, 0x5b, 0xb0,
	0xd0, 0x3f, 0x72, 0x19, 0x97, 0xd5, 0x5b, 0xb5, 0x5c, 0xbd, 0xa4, 0x97, 0xb4, 0xb3, 0x59, 0xd2,
	0xda, 0x72, 0xd6, 0x81, 0xc9, 0x60, 0x7e, 0xec, 0x8e, 0x22, 0x52, 0xcd, 0xd5, 0x40, 0xbd, 0x64,
	0x77, 0x4e, 0x15, 0x36, 0x7e, 0x28, 0xfc, 0x84, 0xb2, 0xf0, 0x28, 0xea, 0x35, 0xfa, 0xc2, 0x6b,
	0x8e, 0x99, 0x4f, 0x02, 0x4e, 0xc2, 0xdd, 0x49, 0x7c, 0xac, 0xc5, 0x2e, 0x27, 0xe1, 0x3b, 0x11,
	0x0c, 0x9b, 0x61, 0xec, 0x13, 0xd9, 0xb0, 0x19, 0x7d, 0xc1, 0xc3, 0x54, 0x61, 0x7d, 0xd4, 0x52,
	0xe1, 0xb2, 0x2e, 0x5b, 0x49, 0xcb, 0xd1, 0xb6, 0xf9, 0x1c, 0x96, 0x28, 0x11, 0xdd, 0x63, 0xc1,
	0x89, 0xac, 0xde, 0x5e, 0x21, 0x3e, 0x4a, 0x15, 0xde, 0x98, 0x4b, 0x85, 0xb7, 0xf4, 0xe2, 0x95,
	0x65, 0x39, 0x77, 0x28, 0x11, 0x87, 0xd9, 0x68, 0xbe, 0x82, 0x15, 0x1e, 0x79, 0x5d, 0x49, 0x82,
	0x31, 0xeb, 0x93, 0x40, 0x56, 0xf3, 0x35, 0x50, 0xcf, 0xdb, 0x8f, 0x53, 0x85, 0xaf, 0x07, 0x4b,
	0x85, 0xb7, 0xf5, 0x39, 0xd7, 0x6c, 0xcb, 0x29, 0xf3, 0xc8, 0xeb, 0x5c, 0xca, 0xbd, 0xad, 0x93,
	0x29, 0x36, 0xbe, 0x4c, 0xb1, 0x71, 0x3e, 0xc5, 0xe0, 0xe4, 0x2b, 0x06, 0xd6, 0x77, 0x00, 0xef,
	0xb7, 0x25, 0xb5, 0x09, 0x65, 0xfc, 0x80, 0xcb, 0xd5, 0x5d, 0x7c, 0x00, 0xb0, 0xb8, 0x3f, 0x18,
	0x04, 0x44, 0xca, 0xf5, 0x65, 0x8c, 0x52, 0x85, 0x1f, 0xb8, 0xbe, 0x3f, 0x62, 0x7d, 0x37, 0x64,
	0x82, 0x77, 0x5d, 0x1d, 0x2f, 0x15, 0xde, 0xd1, 0xb5, 0x37, 0x84, 0xd6, 0x2f, 0x85, 0x5b, 0xff,
	0xf2, 0x53, 0xd7, 0x9d, 0xce, 0x65, 0xf9, 0x0d, 0xb8, 0x9f, 0x00, 0x2c, 0xb5, 0x25, 0x3d, 0xe0,
	0x6f, 0x5d, 0x36, 0x32, 0x39, 0x2c, 0xee, 0xfb, 0x7e, 0xf6, 0xf5, 0x9a, 0xf3, 0x4d, 0xaa, 0x70,
	0x71, 0xc3, 0x76, 0x6f, 0xcd, 0xf6, 0xdf, 0x3c, 0xba, 0xe4, 0x4f, 0x1e, 0xdb, 0x9b, 0xcd, 0x91,
	0x71, 0x36, 0x47, 0xc6, 0xc5, 0x1c, 0x81, 0xf7, 0x09, 0x02, 0xdf, 0x12, 0x04, 0x4e, 0x13, 0x04,
	0x66, 0x09, 0x02, 0x3f, 0x13, 0x04, 0xce, 0x13, 0x64, 0x5c, 0x24, 0x08, 0x7c, 0x5e, 0x20, 0x63,
	0xb6, 0x40, 0xc6, 0xd9, 0x02, 0x19, 0x87, 0xcf, 0xfe, 0x8e, 0x62, 0xd2, 0xbc, 0x7a, 0x47, 0x9a,
	0xa8, 0x57, 0x58, 0x3d, 0x9f, 0xd6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x0e, 0x38, 0x53,
	0x6e, 0x03, 0x00, 0x00,
}

func (this *MsgProtoStake) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgProtoStake)
	if !ok {
		that2, ok := that.(MsgProtoStake)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PubKey, that1.PubKey) {
		return false
	}
	if len(this.Chains) != len(that1.Chains) {
		return false
	}
	for i := range this.Chains {
		if this.Chains[i] != that1.Chains[i] {
			return false
		}
	}
	if !this.Value.Equal(that1.Value) {
		return false
	}
	if len(this.GeoZones) != len(that1.GeoZones) {
		return false
	}
	for i := range this.GeoZones {
		if this.GeoZones[i] != that1.GeoZones[i] {
			return false
		}
	}
	if this.NumServicers != that1.NumServicers {
		return false
	}
	return true
}
func (this *MsgBeginUnstake) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgBeginUnstake)
	if !ok {
		that2, ok := that.(MsgBeginUnstake)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Address, that1.Address) {
		return false
	}
	return true
}
func (this *MsgUnjail) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgUnjail)
	if !ok {
		that2, ok := that.(MsgUnjail)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.RequestorAddr, that1.RequestorAddr) {
		return false
	}
	return true
}
func (this *MsgProtoStake) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&types.MsgProtoStake{")
	s = append(s, "PubKey: "+fmt.Sprintf("%#v", this.PubKey)+",\n")
	s = append(s, "Chains: "+fmt.Sprintf("%#v", this.Chains)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "GeoZones: "+fmt.Sprintf("%#v", this.GeoZones)+",\n")
	s = append(s, "NumServicers: "+fmt.Sprintf("%#v", this.NumServicers)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MsgBeginUnstake) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&types.MsgBeginUnstake{")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MsgUnjail) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&types.MsgUnjail{")
	s = append(s, "AppAddr: "+fmt.Sprintf("%#v", this.RequestorAddr)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMsg(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *MsgProtoStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProtoStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProtoStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumServicers != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.NumServicers))
		i--
		dAtA[i] = 0x28
	}
	if len(m.GeoZones) > 0 {
		for iNdEx := len(m.GeoZones) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.GeoZones[iNdEx])
			copy(dAtA[i:], m.GeoZones[iNdEx])
			i = encodeVarintMsg(dAtA, i, uint64(len(m.GeoZones[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Chains[iNdEx])
			copy(dAtA[i:], m.Chains[iNdEx])
			i = encodeVarintMsg(dAtA, i, uint64(len(m.Chains[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBeginUnstake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBeginUnstake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBeginUnstake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnjail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnjail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnjail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestorAddr) > 0 {
		i -= len(m.RequestorAddr)
		copy(dAtA[i:], m.RequestorAddr)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.RequestorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgProtoStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if len(m.Chains) > 0 {
		for _, s := range m.Chains {
			l = len(s)
			n += 1 + l + sovMsg(uint64(l))
		}
	}
	l = m.Value.Size()
	n += 1 + l + sovMsg(uint64(l))
	if len(m.GeoZones) > 0 {
		for _, s := range m.GeoZones {
			l = len(s)
			n += 1 + l + sovMsg(uint64(l))
		}
	}
	if m.NumServicers != 0 {
		n += 1 + sovMsg(uint64(m.NumServicers))
	}
	return n
}

func (m *MsgBeginUnstake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *MsgUnjail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestorAddr)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func sovMsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MsgProtoStake) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MsgProtoStake{`,
		`PubKey:` + fmt.Sprintf("%v", this.PubKey) + `,`,
		`Chains:` + fmt.Sprintf("%v", this.Chains) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`GeoZones:` + fmt.Sprintf("%v", this.GeoZones) + `,`,
		`NumServicers:` + fmt.Sprintf("%v", this.NumServicers) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MsgBeginUnstake) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MsgBeginUnstake{`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MsgUnjail) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MsgUnjail{`,
		`RequestorAddr:` + fmt.Sprintf("%v", this.RequestorAddr) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMsg(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MsgProtoStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProtoStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProtoStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GeoZones", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GeoZones = append(m.GeoZones, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumServicers", wireType)
			}
			m.NumServicers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumServicers |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBeginUnstake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBeginUnstake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBeginUnstake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnjail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnjail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnjail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestorAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestorAddr = append(m.RequestorAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestorAddr == nil {
				m.RequestorAddr = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsg = fmt.Errorf("proto: unexpected end of group")
)
