// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: servicers.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	github_com_vipernet_xyz_viper_network_types "github.com/vipernet-xyz/viper-network/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
	time "time"
	types "github.com/tendermint/tendermint/abci/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProtoValidator struct {
	Address                 github_com_vipernet_xyz_viper_network_types.Address `protobuf:"bytes,1,opt,name=Address,proto3,casttype=github.com/vipernet-xyz/viper-network/types.Address" json:"address" yaml:"address"`
	PublicKey               []byte                                              `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"public_key" yaml:"public_key"`
	Jailed                  bool                                                `protobuf:"varint,3,opt,name=jailed,proto3" json:"jailed"`
	Paused                  bool                                                `protobuf:"varint,4,opt,name=paused,proto3" json:"paused"`
	Status                  int32                                               `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	Chains                  []string                                            `protobuf:"bytes,6,rep,name=Chains,proto3" json:"chains"`
	ServiceURL              string                                              `protobuf:"bytes,7,opt,name=ServiceURL,proto3" json:"service_url"`
	StakedTokens            github_com_vipernet_xyz_viper_network_types.BigInt  `protobuf:"bytes,8,opt,name=StakedTokens,proto3,customtype=github.com/vipernet-xyz/viper-network/types.BigInt" json:"tokens"`
	GeoZone                 []string                                            `protobuf:"bytes,9,rep,name=GeoZone,proto3" json:"geo_zone"`
	UnstakingCompletionTime time.Time                                           `protobuf:"bytes,10,opt,name=UnstakingCompletionTime,proto3,stdtime" json:"unstaking_time" yaml:"unstaking_time"`
	OutputAddress           github_com_vipernet_xyz_viper_network_types.Address `protobuf:"bytes,11,opt,name=OutputAddress,proto3,casttype=github.com/vipernet-xyz/viper-network/types.Address" json:"output_address,omitempty" yaml:"output_address"`
	ReportCard              ReportCard                                          `protobuf:"bytes,12,opt,name=reportCard,proto3" json:"report_card"`
}

func (m *ProtoValidator) Reset()      { *m = ProtoValidator{} }
func (*ProtoValidator) ProtoMessage() {}
func (*ProtoValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5b9786f59292525, []int{0}
}
func (m *ProtoValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtoValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProtoValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProtoValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoValidator.Merge(m, src)
}
func (m *ProtoValidator) XXX_Size() int {
	return m.Size()
}
func (m *ProtoValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoValidator.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoValidator proto.InternalMessageInfo

// ValidatorSigningInfo defines the signing info for a validator
type ValidatorSigningInfo struct {
	Address github_com_vipernet_xyz_viper_network_types.Address `protobuf:"bytes,1,opt,name=address,proto3,casttype=github.com/vipernet-xyz/viper-network/types.Address" json:"address"`
	// height at which validator was first a candidate OR was unjailed
	StartHeight int64 `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height" yaml:"start_height"`
	// index offset into signed block bit array
	Index int64 `protobuf:"varint,3,opt,name=Index,proto3" json:"index_offset" yaml:"index_offset"`
	// timestamp validator cannot be unjailed until
	JailedUntil time.Time `protobuf:"bytes,4,opt,name=jailed_until,json=jailedUntil,proto3,stdtime" json:"jailed_until" yaml:"jailed_until"`
	// missed blocks counter (to avoid scanning the array every time)
	MissedBlocksCounter int64     `protobuf:"varint,5,opt,name=missed_blocks_counter,json=missedBlocksCounter,proto3" json:"missed_blocks_counter" yaml:"missed_blocks_counter"`
	JailedBlocksCounter int64     `protobuf:"varint,6,opt,name=jailed_blocks_counter,json=jailedBlocksCounter,proto3" json:"jailed_blocks_counter" yaml:"jailed_blocks_counter"`
	PausedUntil         time.Time `protobuf:"bytes,7,opt,name=paused_until,json=pausedUntil,proto3,stdtime" json:"paused_until" yaml:"paused_until"`
}

func (m *ValidatorSigningInfo) Reset()      { *m = ValidatorSigningInfo{} }
func (*ValidatorSigningInfo) ProtoMessage() {}
func (*ValidatorSigningInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5b9786f59292525, []int{1}
}
func (m *ValidatorSigningInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSigningInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSigningInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSigningInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSigningInfo.Merge(m, src)
}
func (m *ValidatorSigningInfo) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSigningInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSigningInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSigningInfo proto.InternalMessageInfo

func (m *ValidatorSigningInfo) GetAddress() github_com_vipernet_xyz_viper_network_types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ValidatorSigningInfo) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *ValidatorSigningInfo) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ValidatorSigningInfo) GetJailedUntil() time.Time {
	if m != nil {
		return m.JailedUntil
	}
	return time.Time{}
}

func (m *ValidatorSigningInfo) GetMissedBlocksCounter() int64 {
	if m != nil {
		return m.MissedBlocksCounter
	}
	return 0
}

func (m *ValidatorSigningInfo) GetJailedBlocksCounter() int64 {
	if m != nil {
		return m.JailedBlocksCounter
	}
	return 0
}

func (m *ValidatorSigningInfo) GetPausedUntil() time.Time {
	if m != nil {
		return m.PausedUntil
	}
	return time.Time{}
}

type ReportCard struct {
	TotalSessions          int64                                              `protobuf:"varint,1,opt,name=TotalSessions,proto3" json:"total_sessions"`
	TotalLatencyScore      github_com_vipernet_xyz_viper_network_types.BigDec `protobuf:"bytes,2,opt,name=TotalLatencyScore,proto3,customtype=github.com/vipernet-xyz/viper-network/types.BigDec" json:"total_latency_score"`
	TotalAvailabilityScore github_com_vipernet_xyz_viper_network_types.BigDec `protobuf:"bytes,3,opt,name=TotalAvailabilityScore,proto3,customtype=github.com/vipernet-xyz/viper-network/types.BigDec" json:"total_availability_score"`
	TotalReliabilityScore  github_com_vipernet_xyz_viper_network_types.BigDec `protobuf:"bytes,4,opt,name=TotalReliabilityScore,proto3,customtype=github.com/vipernet-xyz/viper-network/types.BigDec" json:"total_reliability_score"`
}

func (m *ReportCard) Reset()      { *m = ReportCard{} }
func (*ReportCard) ProtoMessage() {}
func (*ReportCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5b9786f59292525, []int{2}
}
func (m *ReportCard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReportCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReportCard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReportCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCard.Merge(m, src)
}
func (m *ReportCard) XXX_Size() int {
	return m.Size()
}
func (m *ReportCard) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCard.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCard proto.InternalMessageInfo

func (m *ReportCard) GetTotalSessions() int64 {
	if m != nil {
		return m.TotalSessions
	}
	return 0
}

type HistoricalInfo struct {
	Header types.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header"`
	Valset []Validator  `protobuf:"bytes,2,rep,name=valset,proto3" json:"valset"`
}

func (m *HistoricalInfo) Reset()         { *m = HistoricalInfo{} }
func (m *HistoricalInfo) String() string { return proto.CompactTextString(m) }
func (*HistoricalInfo) ProtoMessage()    {}
func (*HistoricalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5b9786f59292525, []int{0}
}
func (m *HistoricalInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalInfo.Merge(m, src)
}
func (m *HistoricalInfo) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalInfo proto.InternalMessageInfo

func (m *HistoricalInfo) GetHeader() types.Header {
	if m != nil {
		return m.Header
	}
	return types.Header{}
}

func (m *HistoricalInfo) GetValset() []Validator {
	if m != nil {
		return m.Valset
	}
	return nil
}


func init() {
	proto.RegisterType((*ProtoValidator)(nil), "x.servicers.ProtoValidator")
	proto.RegisterType((*ValidatorSigningInfo)(nil), "x.servicers.ValidatorSigningInfo")
	proto.RegisterType((*ReportCard)(nil), "x.servicers.ReportCard")
	proto.RegisterType((*HistoricalInfo)(nil), "x.servicers.HistoricalInfo")
}

func init() { proto.RegisterFile("servicers.proto", fileDescriptor_f5b9786f59292525) }

var fileDescriptor_f5b9786f59292525 = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6f, 0x1b, 0xc5,
	0x17, 0xf6, 0xfe, 0xdc, 0xc4, 0xc9, 0xd8, 0x4d, 0xd5, 0x49, 0xf3, 0xcb, 0x2a, 0x42, 0x3b, 0xd6,
	0x22, 0x81, 0x0f, 0xd4, 0x96, 0x9a, 0x03, 0x10, 0x89, 0x43, 0x36, 0x95, 0x20, 0x10, 0x89, 0x32,
	0x49, 0x7a, 0xa8, 0x90, 0x56, 0x6b, 0x7b, 0xb2, 0x19, 0xbc, 0x3b, 0x63, 0xed, 0xcc, 0x86, 0xb8,
	0x17, 0x38, 0x82, 0x90, 0x50, 0x05, 0x17, 0x8e, 0x39, 0xf2, 0x9f, 0xd0, 0x63, 0x8e, 0x15, 0x87,
	0x85, 0x38, 0x12, 0xaa, 0x7c, 0xaa, 0x72, 0xe4, 0x84, 0x76, 0x66, 0x9c, 0x5d, 0x43, 0x8a, 0x4a,
	0x7a, 0x5a, 0xcf, 0xf7, 0xbe, 0xf7, 0xbe, 0x4f, 0x6f, 0xde, 0x1b, 0x83, 0x5b, 0x82, 0x24, 0x47,
	0xb4, 0x47, 0x12, 0xd1, 0x1e, 0x26, 0x5c, 0x72, 0x58, 0x3f, 0x6e, 0x5f, 0x42, 0x6b, 0x77, 0x42,
	0x1e, 0x72, 0x85, 0x77, 0xf2, 0x5f, 0x9a, 0xb2, 0x86, 0x42, 0xce, 0xc3, 0x88, 0x74, 0xd4, 0xa9,
	0x9b, 0x1e, 0x74, 0x24, 0x8d, 0x89, 0x90, 0x41, 0x3c, 0xd4, 0x04, 0xf7, 0xc7, 0x1a, 0x58, 0x7a,
	0x90, 0xff, 0x7a, 0x18, 0x44, 0xb4, 0x1f, 0x48, 0x9e, 0x40, 0x06, 0x6a, 0x9b, 0xfd, 0x7e, 0x42,
	0x84, 0xb0, 0xad, 0xa6, 0xd5, 0x6a, 0x78, 0x7b, 0x93, 0x0c, 0xd5, 0x02, 0x0d, 0x5d, 0x64, 0x68,
	0x69, 0x14, 0xc4, 0xd1, 0x86, 0x6b, 0x00, 0xf7, 0xcf, 0x0c, 0xad, 0x87, 0x54, 0x1e, 0xa6, 0xdd,
	0x76, 0x8f, 0xc7, 0x9d, 0x23, 0x3a, 0x24, 0x09, 0x23, 0xf2, 0xee, 0xf1, 0xe8, 0xb1, 0x3e, 0xdc,
	0x65, 0x44, 0x7e, 0xc9, 0x93, 0x41, 0x47, 0x8e, 0x86, 0x44, 0xb4, 0x4d, 0x6d, 0x3c, 0x15, 0x81,
	0x9b, 0x60, 0xf1, 0x41, 0xda, 0x8d, 0x68, 0xef, 0x13, 0x32, 0xb2, 0xff, 0xa7, 0x14, 0xdf, 0x9c,
	0x64, 0x08, 0x0c, 0x15, 0xe8, 0x0f, 0xc8, 0xe8, 0x22, 0x43, 0xb7, 0xb5, 0x68, 0x81, 0xb9, 0xb8,
	0xc8, 0x82, 0x2e, 0x98, 0xff, 0x22, 0xa0, 0x11, 0xe9, 0xdb, 0xd5, 0xa6, 0xd5, 0x5a, 0xf0, 0xc0,
	0x24, 0x43, 0x06, 0xc1, 0xe6, 0x9b, 0x73, 0x86, 0x41, 0x2a, 0x48, 0xdf, 0xbe, 0x51, 0x70, 0x34,
	0x82, 0xcd, 0x37, 0xe7, 0x08, 0x19, 0xc8, 0x54, 0xd8, 0x73, 0x4d, 0xab, 0x35, 0xa7, 0x39, 0x1a,
	0xc1, 0xe6, 0x9b, 0x73, 0xb6, 0x0e, 0x03, 0xca, 0x84, 0x3d, 0xdf, 0xac, 0xb6, 0x16, 0x35, 0xa7,
	0xa7, 0x10, 0x6c, 0x22, 0xb0, 0x03, 0xc0, 0xae, 0xbe, 0x99, 0x7d, 0xbc, 0x63, 0xd7, 0x9a, 0x56,
	0x6b, 0xd1, 0xbb, 0x35, 0xc9, 0x50, 0xdd, 0xdc, 0x97, 0x9f, 0x26, 0x11, 0x2e, 0x51, 0xe0, 0x21,
	0x68, 0xec, 0xca, 0x60, 0x40, 0xfa, 0x7b, 0x7c, 0x40, 0x98, 0xb0, 0x17, 0x54, 0x1b, 0xee, 0x3f,
	0xcd, 0x50, 0xe5, 0xd7, 0x0c, 0xdd, 0xfb, 0x2f, 0xfd, 0xf5, 0x68, 0xb8, 0xcd, 0x64, 0x6e, 0x4a,
	0xaa, 0x5a, 0x78, 0xa6, 0x32, 0x7c, 0x0b, 0xd4, 0x3e, 0x24, 0xfc, 0x11, 0x67, 0xc4, 0x5e, 0x54,
	0xfe, 0x1b, 0x93, 0x0c, 0x2d, 0x84, 0x84, 0xfb, 0x8f, 0x39, 0x23, 0x78, 0x1a, 0x84, 0xdf, 0x5a,
	0x60, 0x75, 0x9f, 0x09, 0x19, 0x0c, 0x28, 0x0b, 0xb7, 0x78, 0x3c, 0x8c, 0x88, 0xa4, 0x9c, 0xed,
	0xd1, 0x98, 0xd8, 0xa0, 0x69, 0xb5, 0xea, 0xf7, 0xd6, 0xda, 0x7a, 0xb8, 0xda, 0xd3, 0xe1, 0x6a,
	0xef, 0x4d, 0x87, 0xcb, 0x5b, 0xcf, 0x9d, 0x4f, 0x32, 0xb4, 0x94, 0x4e, 0x4b, 0xf8, 0xf9, 0xe4,
	0x5d, 0x64, 0x68, 0x45, 0x5f, 0xe4, 0x2c, 0xee, 0x3e, 0xf9, 0x0d, 0x59, 0xf8, 0x65, 0x7a, 0xf0,
	0x07, 0x0b, 0xdc, 0xfc, 0x34, 0x95, 0xc3, 0x54, 0x4e, 0x07, 0xb3, 0xae, 0xfa, 0x13, 0x4d, 0x32,
	0x64, 0x73, 0x15, 0xf0, 0xcd, 0x38, 0xbe, 0xc3, 0x63, 0x2a, 0x49, 0x3c, 0x94, 0xa3, 0x42, 0x6b,
	0x96, 0x71, 0xed, 0x81, 0x9d, 0xb5, 0x00, 0x77, 0x00, 0x48, 0xc8, 0x90, 0x27, 0x72, 0x2b, 0x48,
	0xfa, 0x76, 0x43, 0xb5, 0x64, 0xb5, 0x5d, 0x5a, 0xc9, 0x36, 0xbe, 0x0c, 0x7b, 0xcb, 0xa6, 0x1f,
	0x75, 0x9d, 0xe2, 0xf7, 0x82, 0xa4, 0x8f, 0x4b, 0xf9, 0x1b, 0x8d, 0x6f, 0x4e, 0x50, 0xe5, 0xa7,
	0x13, 0x54, 0x79, 0x7e, 0x82, 0x2c, 0xf7, 0x97, 0x39, 0x70, 0xe7, 0x72, 0x21, 0x77, 0x69, 0xc8,
	0x28, 0x0b, 0xb7, 0xd9, 0x01, 0x87, 0x9f, 0x83, 0xe9, 0x22, 0x9a, 0xdd, 0xf4, 0x4a, 0xbb, 0x79,
	0xed, 0x4d, 0x34, 0xf9, 0xf0, 0x63, 0xd0, 0x10, 0x32, 0x48, 0xa4, 0x7f, 0x48, 0x68, 0x78, 0x28,
	0xd5, 0x32, 0x56, 0xbd, 0xb7, 0x27, 0x19, 0x9a, 0xc1, 0x2f, 0x32, 0xb4, 0xac, 0x3b, 0x5b, 0x46,
	0x5d, 0x5c, 0x57, 0xc7, 0x8f, 0xd4, 0x09, 0x7e, 0x00, 0xe6, 0xb6, 0x59, 0x9f, 0x1c, 0xab, 0x8d,
	0x34, 0x45, 0x68, 0x0e, 0xf8, 0xfc, 0xe0, 0x40, 0x90, 0x52, 0x91, 0x32, 0xea, 0x62, 0x9d, 0x05,
	0x19, 0x68, 0xe8, 0xbd, 0xf5, 0x53, 0x26, 0x69, 0xa4, 0x76, 0xf6, 0xdf, 0x47, 0xae, 0x63, 0x5a,
	0x3c, 0x93, 0x57, 0xa8, 0x94, 0x51, 0x3d, 0x6e, 0x75, 0x0d, 0xed, 0xe7, 0x08, 0x8c, 0xc1, 0x4a,
	0x4c, 0x85, 0x20, 0x7d, 0xbf, 0x1b, 0xf1, 0xde, 0x40, 0xf8, 0x3d, 0x9e, 0x32, 0x49, 0x12, 0xf5,
	0x10, 0x54, 0xbd, 0xf7, 0x27, 0x19, 0xba, 0x9a, 0x70, 0x91, 0xa1, 0x37, 0xb4, 0xc2, 0x95, 0x61,
	0x17, 0x2f, 0x6b, 0xdc, 0x53, 0xf0, 0x96, 0x46, 0x73, 0x39, 0x63, 0xe8, 0x6f, 0x72, 0xf3, 0x85,
	0xdc, 0x95, 0x84, 0x42, 0xee, 0xca, 0xb0, 0x8b, 0x97, 0x35, 0x3e, 0x2b, 0xc7, 0x40, 0x43, 0xbf,
	0x70, 0xa6, 0x9b, 0xb5, 0x57, 0xef, 0x66, 0x39, 0xaf, 0xe8, 0x66, 0x19, 0x35, 0xdd, 0xd4, 0x90,
	0xea, 0xe6, 0xc6, 0xc2, 0xe5, 0x24, 0xff, 0x51, 0x05, 0xa0, 0xd8, 0x03, 0xf8, 0x1e, 0xb8, 0xb9,
	0xc7, 0x65, 0x10, 0xed, 0x12, 0x21, 0x28, 0x67, 0x7a, 0x8a, 0xab, 0x1e, 0xcc, 0x9f, 0x0a, 0x99,
	0x07, 0x7c, 0x61, 0x22, 0x78, 0x96, 0x08, 0xbf, 0x02, 0xb7, 0x15, 0xb0, 0x13, 0x48, 0xc2, 0x7a,
	0xa3, 0xdd, 0x1e, 0x4f, 0x88, 0xf9, 0xb7, 0xf8, 0xec, 0x9a, 0xcf, 0xe4, 0x7d, 0xd2, 0x9b, 0x64,
	0x68, 0x59, 0xeb, 0x46, 0xba, 0xae, 0x2f, 0xf2, 0xc2, 0xf8, 0x9f, 0x5a, 0xf0, 0x7b, 0x0b, 0xfc,
	0x5f, 0xa1, 0x9b, 0x47, 0x01, 0x8d, 0x82, 0x2e, 0x8d, 0xa8, 0x34, 0x36, 0xaa, 0xca, 0xc6, 0xc3,
	0xd7, 0xb2, 0x61, 0x6b, 0x1b, 0x41, 0xa9, 0xb8, 0xf1, 0xf2, 0x12, 0x55, 0xf8, 0x9d, 0x05, 0x56,
	0x54, 0x08, 0x93, 0x88, 0xce, 0xf8, 0xb9, 0xa1, 0xfc, 0xec, 0xbf, 0x96, 0x9f, 0x55, 0xed, 0x27,
	0x29, 0x6a, 0x1b, 0x3b, 0x57, 0x6b, 0x7a, 0xf1, 0xe9, 0x99, 0x53, 0x79, 0x76, 0xe6, 0x54, 0x5e,
	0x9c, 0x39, 0xd6, 0xd7, 0x63, 0xc7, 0xfa, 0x79, 0xec, 0x58, 0x4f, 0xc7, 0x8e, 0x75, 0x3a, 0x76,
	0xac, 0xdf, 0xc7, 0x8e, 0xf5, 0x7c, 0xec, 0x54, 0x5e, 0x8c, 0x1d, 0xeb, 0xc9, 0xb9, 0x53, 0x39,
	0x3d, 0x77, 0x2a, 0xcf, 0xce, 0x9d, 0xca, 0xa3, 0x77, 0x5f, 0xcd, 0xdb, 0x71, 0xe7, 0xf2, 0x55,
	0xd5, 0x3e, 0xbb, 0xf3, 0x6a, 0x66, 0xd7, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x14, 0xf3, 0xf7,
	0x73, 0x15, 0x09, 0x00, 0x00,
}

func (this *ProtoValidator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProtoValidator)
	if !ok {
		that2, ok := that.(ProtoValidator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Address, that1.Address) {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.Jailed != that1.Jailed {
		return false
	}
	if this.Paused != that1.Paused {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if len(this.Chains) != len(that1.Chains) {
		return false
	}
	for i := range this.Chains {
		if this.Chains[i] != that1.Chains[i] {
			return false
		}
	}
	if this.ServiceURL != that1.ServiceURL {
		return false
	}
	if !this.StakedTokens.Equal(that1.StakedTokens) {
		return false
	}
	if len(this.GeoZone) != len(that1.GeoZone) {
		return false
	}
	for i := range this.GeoZone {
		if this.GeoZone[i] != that1.GeoZone[i] {
			return false
		}
	}
	if !this.UnstakingCompletionTime.Equal(that1.UnstakingCompletionTime) {
		return false
	}
	if !bytes.Equal(this.OutputAddress, that1.OutputAddress) {
		return false
	}
	if !this.ReportCard.Equal(&that1.ReportCard) {
		return false
	}
	return true
}
func (this *ValidatorSigningInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorSigningInfo)
	if !ok {
		that2, ok := that.(ValidatorSigningInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Address, that1.Address) {
		return false
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !this.JailedUntil.Equal(that1.JailedUntil) {
		return false
	}
	if this.MissedBlocksCounter != that1.MissedBlocksCounter {
		return false
	}
	if this.JailedBlocksCounter != that1.JailedBlocksCounter {
		return false
	}
	if !this.PausedUntil.Equal(that1.PausedUntil) {
		return false
	}
	return true
}
func (this *ReportCard) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReportCard)
	if !ok {
		that2, ok := that.(ReportCard)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TotalSessions != that1.TotalSessions {
		return false
	}
	if !this.TotalLatencyScore.Equal(that1.TotalLatencyScore) {
		return false
	}
	if !this.TotalAvailabilityScore.Equal(that1.TotalAvailabilityScore) {
		return false
	}
	if !this.TotalReliabilityScore.Equal(that1.TotalReliabilityScore) {
		return false
	}
	return true
}
func (this *ProtoValidator) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 16)
	s = append(s, "&types.ProtoValidator{")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	s = append(s, "PublicKey: "+fmt.Sprintf("%#v", this.PublicKey)+",\n")
	s = append(s, "Jailed: "+fmt.Sprintf("%#v", this.Jailed)+",\n")
	s = append(s, "Paused: "+fmt.Sprintf("%#v", this.Paused)+",\n")
	s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	s = append(s, "Chains: "+fmt.Sprintf("%#v", this.Chains)+",\n")
	s = append(s, "ServiceURL: "+fmt.Sprintf("%#v", this.ServiceURL)+",\n")
	s = append(s, "StakedTokens: "+fmt.Sprintf("%#v", this.StakedTokens)+",\n")
	s = append(s, "GeoZone: "+fmt.Sprintf("%#v", this.GeoZone)+",\n")
	s = append(s, "UnstakingCompletionTime: "+fmt.Sprintf("%#v", this.UnstakingCompletionTime)+",\n")
	s = append(s, "OutputAddress: "+fmt.Sprintf("%#v", this.OutputAddress)+",\n")
	s = append(s, "ReportCard: "+strings.Replace(this.ReportCard.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ValidatorSigningInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&types.ValidatorSigningInfo{")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	s = append(s, "StartHeight: "+fmt.Sprintf("%#v", this.StartHeight)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "JailedUntil: "+fmt.Sprintf("%#v", this.JailedUntil)+",\n")
	s = append(s, "MissedBlocksCounter: "+fmt.Sprintf("%#v", this.MissedBlocksCounter)+",\n")
	s = append(s, "JailedBlocksCounter: "+fmt.Sprintf("%#v", this.JailedBlocksCounter)+",\n")
	s = append(s, "PausedUntil: "+fmt.Sprintf("%#v", this.PausedUntil)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ReportCard) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&types.ReportCard{")
	s = append(s, "TotalSessions: "+fmt.Sprintf("%#v", this.TotalSessions)+",\n")
	s = append(s, "TotalLatencyScore: "+fmt.Sprintf("%#v", this.TotalLatencyScore)+",\n")
	s = append(s, "TotalAvailabilityScore: "+fmt.Sprintf("%#v", this.TotalAvailabilityScore)+",\n")
	s = append(s, "TotalReliabilityScore: "+fmt.Sprintf("%#v", this.TotalReliabilityScore)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringServicers(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ProtoValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtoValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtoValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ReportCard.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if len(m.OutputAddress) > 0 {
		i -= len(m.OutputAddress)
		copy(dAtA[i:], m.OutputAddress)
		i = encodeVarintServicers(dAtA, i, uint64(len(m.OutputAddress)))
		i--
		dAtA[i] = 0x5a
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.UnstakingCompletionTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.UnstakingCompletionTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintServicers(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x52
	if len(m.GeoZone) > 0 {
		for iNdEx := len(m.GeoZone) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.GeoZone[iNdEx])
			copy(dAtA[i:], m.GeoZone[iNdEx])
			i = encodeVarintServicers(dAtA, i, uint64(len(m.GeoZone[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	{
		size := m.StakedTokens.Size()
		i -= size
		if _, err := m.StakedTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.ServiceURL) > 0 {
		i -= len(m.ServiceURL)
		copy(dAtA[i:], m.ServiceURL)
		i = encodeVarintServicers(dAtA, i, uint64(len(m.ServiceURL)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Chains[iNdEx])
			copy(dAtA[i:], m.Chains[iNdEx])
			i = encodeVarintServicers(dAtA, i, uint64(len(m.Chains[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Status != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintServicers(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintServicers(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorSigningInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSigningInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSigningInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.PausedUntil, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.PausedUntil):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintServicers(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x3a
	if m.JailedBlocksCounter != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.JailedBlocksCounter))
		i--
		dAtA[i] = 0x30
	}
	if m.MissedBlocksCounter != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.MissedBlocksCounter))
		i--
		dAtA[i] = 0x28
	}
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.JailedUntil, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.JailedUntil):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintServicers(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x22
	if m.Index != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintServicers(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReportCard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReportCard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReportCard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalReliabilityScore.Size()
		i -= size
		if _, err := m.TotalReliabilityScore.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TotalAvailabilityScore.Size()
		i -= size
		if _, err := m.TotalAvailabilityScore.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TotalLatencyScore.Size()
		i -= size
		if _, err := m.TotalLatencyScore.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.TotalSessions != 0 {
		i = encodeVarintServicers(dAtA, i, uint64(m.TotalSessions))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HistoricalInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Valset) > 0 {
		for iNdEx := len(m.Valset) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Valset[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintServicers(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServicers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintServicers(dAtA []byte, offset int, v uint64) int {
	offset -= sovServicers(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProtoValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovServicers(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovServicers(uint64(l))
	}
	if m.Jailed {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovServicers(uint64(m.Status))
	}
	if len(m.Chains) > 0 {
		for _, s := range m.Chains {
			l = len(s)
			n += 1 + l + sovServicers(uint64(l))
		}
	}
	l = len(m.ServiceURL)
	if l > 0 {
		n += 1 + l + sovServicers(uint64(l))
	}
	l = m.StakedTokens.Size()
	n += 1 + l + sovServicers(uint64(l))
	if len(m.GeoZone) > 0 {
		for _, s := range m.GeoZone {
			l = len(s)
			n += 1 + l + sovServicers(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.UnstakingCompletionTime)
	n += 1 + l + sovServicers(uint64(l))
	l = len(m.OutputAddress)
	if l > 0 {
		n += 1 + l + sovServicers(uint64(l))
	}
	l = m.ReportCard.Size()
	n += 1 + l + sovServicers(uint64(l))
	return n
}

func (m *ValidatorSigningInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovServicers(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovServicers(uint64(m.StartHeight))
	}
	if m.Index != 0 {
		n += 1 + sovServicers(uint64(m.Index))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.JailedUntil)
	n += 1 + l + sovServicers(uint64(l))
	if m.MissedBlocksCounter != 0 {
		n += 1 + sovServicers(uint64(m.MissedBlocksCounter))
	}
	if m.JailedBlocksCounter != 0 {
		n += 1 + sovServicers(uint64(m.JailedBlocksCounter))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.PausedUntil)
	n += 1 + l + sovServicers(uint64(l))
	return n
}

func (m *ReportCard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalSessions != 0 {
		n += 1 + sovServicers(uint64(m.TotalSessions))
	}
	l = m.TotalLatencyScore.Size()
	n += 1 + l + sovServicers(uint64(l))
	l = m.TotalAvailabilityScore.Size()
	n += 1 + l + sovServicers(uint64(l))
	l = m.TotalReliabilityScore.Size()
	n += 1 + l + sovServicers(uint64(l))
	return n
}

func (m *HistoricalInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Header.Size()
	n += 1 + l + sovServicers(uint64(l))
	if len(m.Valset) > 0 {
		for _, e := range m.Valset {
			l = e.Size()
			n += 1 + l + sovServicers(uint64(l))
		}
	}
	return n
}

func sovServicers(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServicers(x uint64) (n int) {
	return sovServicers(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ProtoValidator) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProtoValidator{`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`PublicKey:` + fmt.Sprintf("%v", this.PublicKey) + `,`,
		`Jailed:` + fmt.Sprintf("%v", this.Jailed) + `,`,
		`Paused:` + fmt.Sprintf("%v", this.Paused) + `,`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`Chains:` + fmt.Sprintf("%v", this.Chains) + `,`,
		`ServiceURL:` + fmt.Sprintf("%v", this.ServiceURL) + `,`,
		`StakedTokens:` + fmt.Sprintf("%v", this.StakedTokens) + `,`,
		`GeoZone:` + fmt.Sprintf("%v", this.GeoZone) + `,`,
		`UnstakingCompletionTime:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.UnstakingCompletionTime), "Timestamp", "timestamppb.Timestamp", 1), `&`, ``, 1) + `,`,
		`OutputAddress:` + fmt.Sprintf("%v", this.OutputAddress) + `,`,
		`ReportCard:` + strings.Replace(strings.Replace(this.ReportCard.String(), "ReportCard", "ReportCard", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ValidatorSigningInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ValidatorSigningInfo{`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`StartHeight:` + fmt.Sprintf("%v", this.StartHeight) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`JailedUntil:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.JailedUntil), "Timestamp", "timestamppb.Timestamp", 1), `&`, ``, 1) + `,`,
		`MissedBlocksCounter:` + fmt.Sprintf("%v", this.MissedBlocksCounter) + `,`,
		`JailedBlocksCounter:` + fmt.Sprintf("%v", this.JailedBlocksCounter) + `,`,
		`PausedUntil:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PausedUntil), "Timestamp", "timestamppb.Timestamp", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ReportCard) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReportCard{`,
		`TotalSessions:` + fmt.Sprintf("%v", this.TotalSessions) + `,`,
		`TotalLatencyScore:` + fmt.Sprintf("%v", this.TotalLatencyScore) + `,`,
		`TotalAvailabilityScore:` + fmt.Sprintf("%v", this.TotalAvailabilityScore) + `,`,
		`TotalReliabilityScore:` + fmt.Sprintf("%v", this.TotalReliabilityScore) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringServicers(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ProtoValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServicers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtoValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtoValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedTokens", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakedTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GeoZone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GeoZone = append(m.GeoZone, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnstakingCompletionTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.UnstakingCompletionTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputAddress = append(m.OutputAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.OutputAddress == nil {
				m.OutputAddress = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportCard", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReportCard.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServicers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServicers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorSigningInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServicers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSigningInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSigningInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.JailedUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedBlocksCounter", wireType)
			}
			m.MissedBlocksCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedBlocksCounter |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedBlocksCounter", wireType)
			}
			m.JailedBlocksCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JailedBlocksCounter |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.PausedUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServicers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServicers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReportCard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServicers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReportCard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReportCard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSessions", wireType)
			}
			m.TotalSessions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSessions |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLatencyScore", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalLatencyScore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAvailabilityScore", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAvailabilityScore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalReliabilityScore", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalReliabilityScore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServicers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServicers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *HistoricalInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServicers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServicers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServicers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Valset = append(m.Valset, Validator{})
			if err := m.Valset[len(m.Valset)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServicers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServicers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServicers(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServicers
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServicers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServicers
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServicers
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServicers
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServicers        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServicers          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServicers = fmt.Errorf("proto: unexpected end of group")
)
